ktor:
  application:
    modules:
      - ru.itmo.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://localhost/"
  audience: "sleep-monitor"
  realm: "Sleep monitor"
  secret: ""
keydb:
  host: "keydb"
  port: 6379
