ktor:
  application:
    modules:
      - ru.itmo.ApplicationKt.module
  deployment:
    port: 8090
  version: 0.6
jwt:
  expiration: 168  # 7 days
  secret: "secret"
keydb:
  host: "keydb"
  port: 6379
